---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mozaik
  name: mozaik
  namespace: infinity
spec:
  ports:
  - name: https
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: mozaik
